# Generated by Django 2.2.5 on 2019-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GadgetsShop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Amazon")),
                ("description", models.TextField(verbose_name="Description")),
                ("rating", models.FloatField(default=0, verbose_name="rating")),
                ("url", models.URLField(verbose_name="url")),
            ],
        )
    ]
