# Generated by Django 2.2.5 on 2019-09-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("webapp", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Amazon")),
                ("description", models.TextField(verbose_name="Description")),
                ("rating", models.FloatField(default=0, verbose_name="Rating")),
                ("url", models.URLField(verbose_name="url")),
            ],
        ),
        migrations.CreateModel(
            name="Laptops",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Brand")),
                ("description", models.TextField(verbose_name="Description")),
                ("price", models.IntegerField(default=0, verbose_name="Price")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.Category",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="GadgetsShop"),
    ]
