# Generated by Django 2.2.5 on 2019-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webapp", "0002_auto_20190910_1253")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, verbose_name="New category"),
        )
    ]
