# Generated by Django 2.2.5 on 2019-09-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("webapp", "0003_auto_20190910_1258")]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "PluralForMyModel"}
        ),
        migrations.AlterModelOptions(
            name="laptops", options={"verbose_name_plural": "PluralForMyModel"}
        ),
    ]
